apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fdt7w000t-java-quarkus 
  janus-idp.io/tekton: fdt7w000t-java-quarkus
  backstage.io/kubernetes-id: fdt7w000t-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdt7w000t-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml